// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/WeiXinao/basic-go/webook/comment/grpc"
	"github.com/WeiXinao/basic-go/webook/comment/ioc"
	"github.com/WeiXinao/basic-go/webook/comment/repository"
	"github.com/WeiXinao/basic-go/webook/comment/repository/dao"
	"github.com/WeiXinao/basic-go/webook/comment/service"
	"github.com/WeiXinao/basic-go/webook/pkg/wego"
)

// Injectors from wire.go:

func Init() *wego.App {
	db := ioc.InitDB()
	commentDAO := dao.NewCommentDAO(db)
	loggerV1 := ioc.InitLogger()
	commentRepository := repository.NewCommentRepo(commentDAO, loggerV1)
	commentService := service.NewCommentSvc(commentRepository)
	commentServiceServer := grpc.NewGrpcServer(commentService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxServer(commentServiceServer, client, loggerV1)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}
