apiVersion: v1
# 这个是指 我 k8s 有哪些 volume
kind: PersistentVolume
metadata:
  name: my-local-pv-v1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/k8s/mysql"