db:
  dsn: "root:123456@tcp(192.168.5.4:3307)/webook"

redis:
  addr: "192.168.5.4:6379"

memcached:
  addr: "192.168.5.4:11211"

kafka:
  addr:
    - "192.168.5.3:9094"

etcd:
  addrs:
    - "192.168.5.3:2379"

grpc:
  client:
    intr:
      addr: "etcd:///service/interactive"