// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/WeiXinao/basic-go/webook/comment/grpc"
	"github.com/WeiXinao/basic-go/webook/comment/ioc"
	"github.com/WeiXinao/basic-go/webook/comment/repository"
	"github.com/WeiXinao/basic-go/webook/comment/repository/dao"
	"github.com/WeiXinao/basic-go/webook/comment/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitGRPCServer() *grpc.CommentServiceServer {
	gormDB := InitTestDB()
	commentDAO := dao.NewCommentDAO(gormDB)
	loggerV1 := ioc.InitLogger()
	commentRepository := repository.NewCommentRepo(commentDAO, loggerV1)
	commentService := service.NewCommentSvc(commentRepository)
	commentServiceServer := grpc.NewGrpcServer(commentService)
	return commentServiceServer
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewCommentDAO, repository.NewCommentRepo, service.NewCommentSvc, grpc.NewGrpcServer)

var thirdProvider = wire.NewSet(ioc.InitLogger, InitTestDB)
